### ISSUE TITLE
trainModel runtime error

### ISSUE THREAD

**Issue by samk3570** [lagelab/quack#2]
[1] "MODEL: Quackv1.3-quack_skinsunexposed-Generalstringent853Pathways"
[1] "% complete: 1"
[1] "--Completed modelingAndConnInfoFile"
Error in gzfile(file, "wb") : cannot open the connection
Calls: trainModel -> save -> gzfile
In addition: Warning message:
In gzfile(file, "wb") :
  cannot open compressed file 'R/sysdata.rda', probable reason 'No such file or directory'
Execution halted

I am getting the above error, and can you check what might cause "Error in gzfile(file, "wb") : cannot open the connection"?

**Comment by lagelab** [comment]
Fixed in branch ranger.
